### ISSUE TITLE
회원가입 페이지 만들기

### ISSUE THREAD

**Issue by devSoyoung** [siosio34/timeline-frontend#1]
### Required Field
* 이메일 아이디
* 사용자 이름
* 비밀번호
* 지역 : 서울, 경기 (큰 지역만) select에 고정해두기
* 학교 : string으로 직접 입력
* 생년월일 : 여섯자리 입력으로 고정

### TODO
- [x] ~~아이디 중복검사 기능(버튼 클릭) 추가~~ : 별도의 이슈로 처리
- [x] validation 체크 : 필수 입력란 여부, 비밀번호 길이
- [x] 회원가입 버튼 클릭 시 서버에 전송
