### ISSUE TITLE
포스트 등록 기능 만들기

### ISSUE THREAD

**Issue by devSoyoung** [siosio34/timeline-frontend#5]
### Required Field
* 컨텐츠 입력하는 영역
* 사진 업로드하는 영역
* 저장 버튼

### TODO
- [x] 사진 업로드 시 미리보기 제공
- [x] 저장 성공/실패 시 modal로 결과 알림 구현
- [x] 이미지 업로드는 최대 4장
- [x] 미리보기 제공

### 참고할 디자인
![image](https://user-images.githubusercontent.com/42922453/61511380-8bf94780-aa31-11e9-9260-36dec2811f12.png)

이미지 아이콘을 누르면 업로드 영역이 표시되도록

### 사진 업로드
<img src="https://user-images.githubusercontent.com/42922453/61180075-5fb58380-a64b-11e9-85b8-d6fb17ae25fa.png" width="500px">

링크 : [https://ant.design/components/upload/#header](https://ant.design/components/upload/#header)

### 저장 성공/실패 여부
<img src="https://user-images.githubusercontent.com/42922453/61180082-7bb92500-a64b-11e9-93c9-9c56fa485a74.png" height="400px">
